[package]
name = "bilibili-radio-desktop"
version = "0.1.5"
description = "Bilibili Radio desktop client"
authors = ["ourhome-macro"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
